name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GO_VERSION: '1.21'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        
    - name: Run tests
      run: make test
      
    - name: Build all platforms
      run: make build-all
      
    - name: Generate checksums
      run: |
        cd bin/
        sha256sum * > checksums.txt
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ignorer_linux
          bin/ignorer_darwin
          bin/ignorer.exe
          bin/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 