name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: read

env:
  GO_VERSION: '1.21'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        
    - name: Run tests
      run: make test
      
    - name: Build all platforms
      run: make build-all
      
    - name: Generate checksums
      run: |
        cd bin/
        sha256sum * > checksums.txt
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ignorer_linux
          bin/ignorer_darwin
          bin/ignorer.exe
          bin/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Homebrew Formula
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Create tarball URL
        TARBALL_URL="https://github.com/ignorer/ignorer/archive/v${VERSION}.tar.gz"
        
        # Download tarball and calculate SHA256
        curl -sL "$TARBALL_URL" -o "ignorer-${VERSION}.tar.gz"
        SHA256=$(sha256sum "ignorer-${VERSION}.tar.gz" | cut -d' ' -f1)
        
        # Update the Homebrew formula
        sed -i "s|url \".*\"|url \"$TARBALL_URL\"|g" Formula/ignorer.rb
        sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|g" Formula/ignorer.rb
        
        # Clean up
        rm "ignorer-${VERSION}.tar.gz"
        
        echo "Updated Homebrew formula for version $VERSION with SHA256: $SHA256"
        
    - name: Commit and Push Homebrew Formula Update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/ignorer.rb
        git commit -m "Update Homebrew formula to ${GITHUB_REF#refs/tags/}" || exit 0
        git push origin HEAD:main || git push origin HEAD:master 