name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: read
  pull-requests: write

env:
  GO_VERSION: '1.21'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        
    - name: Run tests
      run: make test
      
    - name: Build all platforms
      run: make build-all
      
    - name: Generate checksums
      run: |
        cd bin/
        sha256sum * > checksums.txt
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ignorer_linux
          bin/ignorer_darwin
          bin/ignorer.exe
          bin/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Homebrew Formula and Create PR
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        BRANCH_NAME="homebrew-update-v${VERSION}"
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create and checkout new branch from main
        git fetch origin main
        git checkout -b "${BRANCH_NAME}" 
        
        # Create tarball URL
        TARBALL_URL="https://github.com/manucodin/ignorer/archive/v${VERSION}.tar.gz"
        
        # Download tarball and calculate SHA256
        curl -sL "$TARBALL_URL" -o "ignorer-${VERSION}.tar.gz"
        SHA256=$(sha256sum "ignorer-${VERSION}.tar.gz" | cut -d' ' -f1)
        
        # Update the Homebrew formula
        sed -i "s|url \".*\"|url \"$TARBALL_URL\"|g" Formula/ignorer.rb
        sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|g" Formula/ignorer.rb
        
        # Clean up
        rm "ignorer-${VERSION}.tar.gz"
        
        echo "Updated Homebrew formula for version $VERSION with SHA256: $SHA256"
        
        # Commit changes
        git add Formula/ignorer.rb
        git commit -m "Update Homebrew formula to v${VERSION}" || exit 0
        
        # Push the branch
        git push origin "${BRANCH_NAME}"
        
        # Create Pull Request using GitHub CLI
        gh pr create \
          --title "🍺 Update Homebrew formula to v${VERSION}" \
          --body "Automated update of Homebrew formula for release v${VERSION}

        **Changes:**
        - Updated formula URL to point to v${VERSION} release
        - Updated SHA256 checksum to ${SHA256}
        
        This PR was automatically created by the release workflow." \
          --head "${BRANCH_NAME}" \
          --base main \
          --assignee "@me"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 